# Generated by Django 3.0 on 2020-03-30 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('xmpp', models.CharField(max_length=100)),
                ('matrix', models.CharField(max_length=100)),
                ('pgp', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blogentry',
            name='title',
            field=models.CharField(default='Title und so!', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Author'),
        ),
    ]
