# Generated by Django 3.0 on 2020-03-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_service_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='login',
            field=models.CharField(default='username', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
    ]
