# Generated by Django 3.1.2 on 2022-04-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200330_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatViewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('confirmed', models.BooleanField()),
                ('acknowledged', models.BooleanField()),
                ('canceled', models.BooleanField()),
            ],
        ),
    ]
