# Generated by Django 3.1.2 on 2020-10-15 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isWorking', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateTimeField(default=datetime.datetime(2020, 10, 15, 14, 19, 32, 347872, tzinfo=datetime.timezone.utc), verbose_name='Beginn')),
                ('dateTo', models.DateTimeField(null=True, verbose_name='Ende')),
                ('duration', models.IntegerField(null=True, verbose_name='Dauer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktime.category', verbose_name='Kategory')),
            ],
        ),
    ]
