# Generated by Django 3.1.2 on 2020-10-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0003_auto_20201015_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-dateFrom']},
        ),
        migrations.AlterField(
            model_name='work',
            name='dateTo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dauer'),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Typ'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
