# Generated by Django 3.1.2 on 2020-10-15 20:22

from django.db import migrations, models
import worktime.models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0005_auto_20201015_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[(worktime.models.Types['WORK'], 'Arbeit'), (worktime.models.Types['ILL'], 'Krank'), (worktime.models.Types['FREE'], 'Feiertag'), (worktime.models.Types['HOLIDAY'], 'Urlaub')], max_length=255, verbose_name='Typ'),
        ),
    ]
