# Generated by Django 4.2.5 on 2023-09-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worktime", "0006_auto_20201015_2222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="work",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
